### ISSUE TITLE
Tailwind CSS support

### ISSUE THREAD

**Issue by jsblair9** [coral-xyz/backpack#1008]
Would love to be able to utilize [Tailwind](https://tailwindcss.com/) inside of Backpack!

**Comment by hkirat** [comment]
I think we might be getting close to be able to support this with https://github.com/coral-xyz/backpack/pull/1142
After discussing with @peterpme , we should be able to support this on both mobile and web.
On mobile though we'll have to proxy tailwind classes through a library like https://github.com/vadimdemedes/tailwind-rn

Does it make sense for the sdk to allow specifying these separately from native classes?
Maybe something like - 

```js
    <Button
       tailwindClasses={"bg-blue-200 px-3 py-1 rounded-full"}
    />
```

Thinking slightly ahead we might want to allow users to specify these saparately for mobile and web since they can render very differently on both (you might need a px-2 on web but px-5 (class that controlls padding) on mobile because of how pixels are present on both the devices)

Maybe something like

```js
    <Button
       tailwindWebClasses={"bg-blue-200 px-3 py-1 rounded-full"}
       tailwindMobileClasses={"bg-blue-200 px-10 py-5 rounded-full"}
    />
```



```

**Comment by jim4067** [comment]
@hkirat this sound amazing. 

sidetrack, is there a workaround to use `.css` styling. I tried but importing files seems to be impossible

**Comment by armaniferrante** [comment]
Moving to react-native. Closing.
