### ISSUE TITLE
react-xnft: add swipe gestures

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1264]
I should be able to swipe left and right with my trackpad on macOS to scroll through this horizontal list on the Tiexo xNFT.

<img width="363" alt="Screen Shot 2022-10-25 at 9 44 24 AM" src="https://user-images.githubusercontent.com/6990215/197790083-20933091-495b-4f67-9c98-0916873da7b8.png">

**Comment by hkirat** [comment]
I think this is by design, they've hidden the scroll deliberately (will confirm with them). If I remove the `overflow: hidden` swiping works
<img width="909" alt="Screenshot 2022-10-26 at 7 01 02 PM" src="https://user-images.githubusercontent.com/8079861/198039713-9ec71464-8825-4015-89bd-a2eed49010dd.png">

**Comment by hkirat** [comment]
Confirmed that this was done intentionally because of `dirty scrollbars` and should go away when the users wrap their `View` around the new `Scrollbars`
