### ISSUE TITLE
blockchain selector not shown on username recovery

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1485]
steps:

* download and open backpack
* go through username recovery flow

and the blockchain selector is never shown. It just creates a Solana wallet with no Ethereum wallet. Instead, the blockchain selector should be shown

**Comment by tomlinton** [comment]
The reason for this is that the blockchains that should be configured are known already, as they are stored in the auth worker db.

We also know which public keys we want to recover, but the reason this got punted is because I'm not sure how we figure out where the public keys are, but its probably:

- If a mnemonic based wallet, we search the derivation paths.
- If a ledger we ask them to open the app and search
- Unsure how to deal with imported private keys (currently not possible anyway)

Alternatively, we give the user a choice of public keys, and them we associate those public keys with the username, replacing the public keys that currently exist.

**Comment by armaniferrante** [comment]
This issue is no longer relevant. Instead, on recovery, we will walk the user through all registered pubkeys (via https://github.com/coral-xyz/backpack/issues/1599) and prompt for recovery.
