### ISSUE TITLE
backpack doesn't lock after closed even with setting

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#1940]
Seems to only happen when you lock/unlock super quickly.

https://user-images.githubusercontent.com/6990215/208818699-b4b257b2-cef8-4588-bd78-0bf030ba9361.mov

**Comment by wentokay** [comment]
There's a [0.5 second delay](https://github.com/coral-xyz/backpack/blob/ce2da329efbe87ff8da46e47ea70a1894c4f9aea/packages/background/src/backend/keyring/index.ts#L117-L120) on the autolock after closing Backpack.

This is so that when you launch popout mode it remains unlocked (when the popup window opens, the 0.5 second countdown is cancelled).

If it locked instantly on close then the popup window would open in the locked state.

**Comment by wentokay** [comment]
Closing for now but can reopen if you think it needs to be changed or better documented @armaniferrante
