### ISSUE TITLE
Add usernames to review send drawer

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#2802]
if someone is a backpack user, add their username between avatar and truncated address in "review send" drawer

left: current / right: proposed

<img width="855" alt="Screenshot 2023-02-17 at 3 54 40 PM" src="https://user-images.githubusercontent.com/321395/219801182-af8a5d7b-ea01-4aaf-9ad2-1d7b52e62f6b.png">

ignore the other changes you see in the screenshot, they are or will be part of other tickets :)

**Comment by wentokay** [comment]
<img width="487" alt="Screenshot 2023-03-06 at 15 40 30" src="https://user-images.githubusercontent.com/101902546/223281625-5f507a65-a4a4-44ae-817b-f64b3a43e313.png">

@trucy do you have any thoughts about what should be shown when a user is sending to another of their own wallets?

I feel it might be useful to show the wallet name they are `sending from`, as well as the wallet name they are `sending to`. This is the current screenshot of progress from doing this issue but it's broken rn because it's showing `@Wallet 2`

**Comment by wentokay** [comment]
@trucy this is what I now have in #3198, let me know what you think, it would be good to merge it soon if possible as it changes a few different files

it doesn't show the username that it is sending from, but it shows the wallet name instead (and the user avatar)


### sending from...

another solana user | another ethereum user | a different wallet owned by the user
-------|------|-------
<img width="487" alt="Screenshot 2023-03-06 at 16 26 12" src="https://user-images.githubusercontent.com/101902546/223287490-2d44c61d-0abd-49c8-866f-7a60f24cdbb6.png">|<img width="487" alt="Screenshot 2023-03-06 at 16 27 31" src="https://user-images.githubusercontent.com/101902546/223287503-b8ec2b79-e80b-4da3-abe9-3cfbe31271d2.png">|<img width="487" alt="Screenshot 2023-03-06 at 16 26 00" src="https://user-images.githubusercontent.com/101902546/223287532-8fbb5254-e8cd-492d-8288-65f9ac689824.png">

**Comment by trucy** [comment]
Thanks! What you suggested using wallet names looks good to me. Any suggestions I have off the cuff would require design tweaks to this page that don't seem worth it right now and this is already a nice improvement on what we have.
