### ISSUE TITLE
autolock settings not working properly

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#3027]
Lots of reports in Discord of autolock not behaving, maybe related to https://github.com/coral-xyz/backpack/issues/2985

**Comment by wentokay** [comment]
are there any specific issues, or have you been able to reproduce anything you've seen?

I've found these searching for 'autolock' messages (since the last chrome store publish) -

"despite me having autolock set to off, i get locked out of backpack (i.e. needing a PW) everytime i click away" - #2985?
"It autolocks within in 2/3 mins" - #2895?
"autolocking is not working well" - ?

**Comment by tomlinton** [comment]
Nothing specific, just needs digging into. It might all just be #2985.

**Comment by wentokay** [comment]
`never` will ask for a password after opening backpack if the service worker has died, i.e. it hasn't been polled with a keepalive message.

So this will always happen if the user quits the browser application itself and possibly if the user has backpack closed for a certain amount of time, although I haven't been able to reproduce that locally

If that's the case it might be best to remove never as an option altogether.

Other wallets using chrome manifest v2 won't have this problem because it's a special type of background script and not a service worker that's designed to be ephemeral.

**Comment by tomlinton** [comment]
Other reports:

`I'm also using brave (on linux) and constantly have to enter password, regardless of lock settings`

`it the auto lock timer not fully operational yet? tried diff times and even never and it gets locked after closing regardless of setting`

You can reproduce this behaviour with the `Update on reload` setting in dev tools, but I don't think that is what is happening here. It does seem like something is killing the service worker for some reason. 

<img width="465" alt="Screenshot 2023-03-02 at 9 21 37 AM" src="https://user-images.githubusercontent.com/489202/222256735-a4282cad-6503-4085-be15-49424f233611.png">

**Comment by wentokay** [comment]
[chrome alarms](https://github.com/w3c/webextensions/issues/72#issuecomment-1252627332) might help in some cases but not in this case where the SW appears to be terminating with the popup

**Comment by armaniferrante** [comment]
Going to change to p3. I'm not sure if there's anything we can do about this given the ephemeral nature of service workers. Please feel free to comment if you disagree.
