### ISSUE TITLE
notifications should have number of notifications

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3034]

**Comment by hkirat** [comment]
Could you elaborate on this @armaniferrante ?

**Comment by armaniferrante** [comment]
Going to move this to priority 2. But it would be awesome to get done soon after the priority 1s are handled.

**Comment by hkirat** [comment]
This should already be there if this is what you mean
![Screenshot 2023-03-03 at 4 49 19 AM](https://user-images.githubusercontent.com/8079861/222585269-6324172d-ee0a-47e2-b1c6-c0b11aac4139.jpg)

Notifications are rolling out slowly because the `mad list` group is notifying 4k people for all messages which is why you might not be seeing them roll in at a fast pace

But when they come, the bubble should have the count

**Comment by armaniferrante** [comment]
That's exactly what I mean. Would be great to get this in if it's done already.

**Comment by hkirat** [comment]
It's already in master (has been for a while)

**Comment by hkirat** [comment]
Do you not see it when you receive new notifications?

**Comment by hkirat** [comment]
(Only happens for new notifications, once you open it it goes away)
