### ISSUE TITLE
The Select Token screen doesn't utilize the full height of the screen

### ISSUE THREAD

**Issue by AFZL210** [coral-xyz/backpack#3593]
This may not be an issue but can anyone from the team confirm this?
the select token box seems a little weird as it doesn't take up the remaining height and just leaves white space

https://user-images.githubusercontent.com/79896602/229877721-0b973054-3d38-430b-bd62-b3b6d0f9ca27.mp4

**Comment by theDheerajjha** [comment]
I'd like to work on this. Please assign it to me

**Comment by AdityaSamantaroy** [comment]
I looked into this issue and it seems like it is being done intentionally. If number of rows are greater than 100, the component height is that of 6 rows only.

![image](https://user-images.githubusercontent.com/54908831/230230346-018cace2-a1f8-40da-b0cd-e790f28e9cae.png)

I checked for the case of there being less than 100 rows (7 in this case), and as expected we can see 7 rows -
![image](https://user-images.githubusercontent.com/54908831/230230000-43e41c17-acf9-4dd6-b942-43696eae0c9d.png)

Maybe this behavior can be changed so that the Select Token box occupies maximum vertical area as per the window, rather than being limited to 6 rows in the case of >100 total rows?
