### ISSUE TITLE
Friend request card in notifications always shows as unread.

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3723]
This friend request card always displays as unread.
On the friends list, there are no pending requests.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/232886532-7fffa31d-939d-43aa-8a44-6202670a6988.png">
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4157473/232886590-e5ca3b30-b4e6-4be0-8452-cbadb76bf16a.png">

**Comment by nc1337** [comment]
@aarongillett  i would like to take this up. :)

**Comment by aarongillett** [comment]
It’s all yours @nc1337. Thanks for contributing!

**Comment by nc1337** [comment]
@aarongillett How shall i be able to reproduce this? Is there any documentation that i can go through to start working. I have done the setup and have also got the `dev extension` of `backpack` up and running . 
I have tried looking into the main docs, but couldn't find anything quite useful. Kindly guide me in right direction to solve this issue

**Comment by nc1337** [comment]
@aarongillett How shall i be able to reproduce this? Is there any documentation that i can go through to start working. I have done the setup and have also got the `dev extension` of `backpack` up and running . 
I have tried looking into the main docs, but couldn't find anything quite useful. Kindly guide me in right direction to solve this issue

**Comment by nc1337** [comment]
@aarongillett Could you kindly convey what kind of behaviour is intended in this scenario? Thanks :)

**Comment by aarongillett** [comment]
@nc1337 If you open the notifications panel and see the unread request, its status should change from _unread_ to _read_ but remain the blue accent colour. If you close and re-open the panel, the card should now be in a read/seen state, and have a white background (in light mode), similar to how messages works:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/4157473/233443573-f773e815-75d7-44a8-a8aa-41eba962fcb2.png">

**Comment by nc1337** [comment]
@aarongillett 
After some investigation, i am able to  figure out the problem but i don't know which direction to take. Below are those investigation points:
1. This issue is due to the `notification.viewed` property not getting set to `false` even after the call to  `notifications/seen` api which ideally should update the notification status to `viewed = true` in my opinion.
2. Also, there is a call to `setUnreadCount` which sets the `unreadCount` to `0` which is not being used in the `Notification.tsx`. Also  
3. The call to fetch `notfications` uses `useRecentNotifications` hook which always fetched the value from `atoms` which is `cached` on the basis of `userId`.

Also Including @hkirat as he is author of the Notification changes which i am seeing. 
Could you please also verify whether my understanding is right or not?
