### ISSUE TITLE
Can't click next after pasting amount into token send form 

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#3829]
From @steveluscher:

Bug report. I pasted a value into this UI. The ‘review’ button didn't light up. I pressed backspace on the last value and typed it in again. Still didn't light up. Deleted everything but two decimals. Lit up. Typed in the rest and pressed ‘review.’ The rest of the digits didn't appear in the ‘review’ sheet.

Eventually ended up erasing the entire value and typing it in manually. That worked.

![image](https://user-images.githubusercontent.com/6990215/235008329-15c28edb-3da4-42a0-a394-75812ec5123f.png)

**Comment by Merdi-kim** [comment]
I would like to explore the source of this and fix it. Can I take on this issue? @armaniferrante

**Comment by steveluscher** [comment]
Go for it, @Merdi-kim!

![Do or do not, there is no try](https://user-images.githubusercontent.com/13243/235053307-16255896-c199-4980-ab31-644a64257e48.gif)

**Comment by Merdi-kim** [comment]
I'm on it

**Comment by Rakeshrockz** [comment]
Did you paste the value directly into an input field, or did you use a different method to input the value? @steveluscher

**Comment by steveluscher** [comment]
Pasted, Command-V. Check out my bad repro steps in the description above!

**Comment by Merdi-kim** [comment]
@armaniferrante I have fixed this issue and opened a PR. Kindly check it out when possible


**For documentation purposes**:  After research, I came to find out that the "Review" button stayed disabled because the amount that was pasted in the UI had more than 9 decimal digits yet Solana can only have 9. What I mean is **1SOL = 1000000000 lamports** which means you can not fractionize it more than that. But then the bug was that if you type the amount manually and do not paste it, the "Review" button stays enabled even if you go up to 20 decimal digits. The reason why it stayed enabled is that the state of the amount did not update after the 9 decimal digits(it sort of cached the amount and didn't update it). But the issue was fixed by disabling the review button whenever the decimal places of the amount surpass the decimal places allowed for a particular token(9 for Solana, 18 for ETH) no matter if the amount was pasted on the UI or written manually.
