### ISSUE TITLE
After uninstalling an xNFT, I don't see the state change until I close and reopen the extension

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3889]
After uninstalling an xNFT, it still shows up in my xNFT settings and in the Applications tab until I close and reopen the extension

**Comment by Merdi-kim** [comment]
@trucy can I work on this issue and investigate it further?

**Comment by philosphi** [comment]
After some investigation, I could use some input from the team on the best path forward. It looks like we indeed are not updating the UI state of the xNFTs when the uninstall is completed, so the changes aren't reflected in the UI unless the extension is reloaded. I believe if we want to display these changes within the same user session, we'd have to fetch the latest xnfts contents and update the UI state accordingly. 

In referencing the send flow for typical NFTs, I noticed we are regularly updating the NFTs state by polling the API every 10s. So after confirming a transaction, the UI will eventually be updated with the new change in 10-20s. My question is do we want to implement a similar sync model for the xNFT state by polling for its updates as well? If so, it seems like we'd want to decrease the polling interval so that it takes less time before users see their changes reflected. Another side effect with the current polling model is that if the user has not already closed out of the transaction modal, by the time the next polled update is made, it may force the UI to rerender and a non-existent details page for the xNFT would remain. (this is a current issue in the NFT flow. screen recording of this is in the next comment)

Another option I'm exploring is to manually perform a fetch for the xNFT contents once the transaction is completed (and/or when the user has exited the transaction modal) and update the state of the xNFTs. This way the user will be able to see the changes reflected through the UI instantly.

Here is an outline for this manual fetch which I'm basing on the polling mechanism for NFT updates. 

1. Settings/Xnfts/Detail.tsx: on uninstall confirmation, emit `UI_RPC_XNFTS_UPDATE` event to the server-ui 
2. server-ui: handle `UI_RPC_XNFTS_UPDATE` event and call a `xnftUpdate` function through the backend core client 
3. backend/core.ts: in `xnftUpdate`, emit `NOTIFICATION_XNFTS_UPDATE` event to solana/ethereum-connection 
4. solana/etheruem connection: handle `NOTIFICATION_XNFTS_UPDATE` event and call `fetchXnfts(provider, wallet, isDropZoneWallet)`  to fetch xNFT contents. emit `NOTIFICATION_XNFTS_DID_UPDATE` event along with fetched xNFT contents 
5. Notifications.tsx: receive event and call a `useUpdateXnft` hook with new xNFT contents
6. useUpdateXnft.tsx: update xnft atom with new xNFT contents. 

Please let me know if there are any concerns or other suggestions with this approach! Thanks

**Comment by philosphi** [comment]
In my investigation, I also uncovered some issues with the current send flow for NFTs. Happy to create these issues if it all checks out with the team. 

1. when a user sends an NFT through the menu options of the NFT rather than the NFT details page, closing out of the transaction modal does not navigate the user back to the root NFT tab since the user is already at the root level. Instead, the send drawer of the non-existent NFT still remains. I believe the intention is to direct it to the root tab view

https://github.com/coral-xyz/backpack/assets/33209733/6401d506-41bf-4b68-a2f9-1af5a97c0ff7


2. When switching between accounts within the same user session, the polling mechanism continues to poll for data associated with the previous account (the one that the user signed in as) instead of the currently active account. As a result, the NFT contents belonging to the previous account are reflected in the UI when sending NFTs between the accounts. Seems like it should poll against the account that's currently active instead 

3. (mentioned in previous comment) After sending an NFT, if the user has not already closed out of the transaction modal, the state will eventually update via polling which forces the UI to rerender and a blank details page for the non-existent NFT remains. Could look into ways to prevent these components from forcefully re-rendering when their subscribed atom is updated. 

https://github.com/coral-xyz/backpack/assets/33209733/d6e9438d-bb6f-4e92-a0f4-9af75a12a696
