### ISSUE TITLE
Mobile view for backpack.app/downloads

### ISSUE THREAD

**Issue by trucy** [coral-xyz/backpack#3958]
![A3B6BB57-0311-4595-B79B-071DE8D7140B](https://github.com/coral-xyz/backpack/assets/321395/18475ed3-2ad9-4517-b0b4-3e701363b31b)

just need to stack 🙏

**Comment by mrb1nary** [comment]
![image](https://github.com/coral-xyz/backpack/assets/55779046/c80ecd6b-d327-42d0-ae01-5a8fe92a071a)

### Suggestion
Hey @trucy instead of stacking the buttons one below the other we can do this. The user need not to scroll down at all as every button would be accessible within the viewport. Or should we stick to your idea?
