### ISSUE TITLE
the wallet name should be in the To field when sending eth to another owned wallet

### ISSUE THREAD

**Issue by wentokay** [coral-xyz/backpack#4080]
when sending solana (+ SPL tokens) between wallets owned by a user, the `To` field has the name of the wallet it is being sent to

ui | wallets 
---|---
<img width="487" alt="Screenshot 2023-05-29 at 19 26 59" src="https://github.com/coral-xyz/backpack/assets/101902546/d3b97c78-a7b9-4635-bd8f-f8c47d6cdba3">|<img width="361" alt="Screenshot 2023-05-29 at 19 32 41" src="https://github.com/coral-xyz/backpack/assets/101902546/6d691d6d-a40c-4622-9c1c-f5d801bafc0e">

but when sending eth (+ ERC20 tokens) the `To` field shows the username and not the name of the wallet

ui | wallets 
---|---
<img width="487" alt="Screenshot 2023-05-29 at 19 26 28" src="https://github.com/coral-xyz/backpack/assets/101902546/33369c0a-4765-4dec-beeb-03391e6823d8">|<img width="357" alt="Screenshot 2023-05-29 at 19 32 37" src="https://github.com/coral-xyz/backpack/assets/101902546/be9cda26-4761-4c43-9c08-40f5121810eb">

**Comment by AFZL210** [comment]
@wentokay, can I work on this? Most probably, the reason is in the `destinationUser`. We are using the wallet name for Solana and the wallet address for Ethereum.

Solana:
https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx#L43

Ethereum:
https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Ethereum/index.tsx#L41
