### ISSUE TITLE
Can't use window.xnft.openWindow()

### ISSUE THREAD

**Issue by Aiyualive** [coral-xyz/backpack#4087]
When I am using `window.xnft.openWindow()` to open a new tab in the browser, I get the error:

> Blocked opening 'https://www.twitter.com/blessed_burgers' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

It might be related to to this commit
[https://github.com/coral-xyz/backpack/commit/1606c325e2e910353eba0bc8b7988103d3ea5ce5](https://github.com/coral-xyz/backpack/commit/1606c325e2e910353eba0bc8b7988103d3ea5ce5)

I was able to use `window.xnft.openWindow()` fine a few weeks ago I believe

Issue exists for both Chrome and Brave, I have not tested Firefox though

**Comment by Manish254252** [comment]
hello there 

Does anyone how to solve this 

@coral-xyz/common:build: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

@coral-xyz/common:build: ERROR: command finished with error: command (D:\Newfolder\backpack\packages\common) yarn run build exited (1)

**Comment by wentokay** [comment]
@Aiyualive I believe you can use `window.open` now, or in the upcoming release

related PR https://github.com/coral-xyz/backpack/pull/4085
