### ISSUE TITLE
escape handler on custom endpoint input crashes wallet

### ISSUE THREAD

**Issue by tomlinton** [coral-xyz/backpack#831]
<img width="498" alt="Screen Shot 2022-09-23 at 11 18 11 AM" src="https://user-images.githubusercontent.com/489202/191867641-e9c2c2c2-db09-4a61-98ff-7f7f70938062.png">

Hit ESC

<img width="380" alt="Screen Shot 2022-09-23 at 11 17 56 AM" src="https://user-images.githubusercontent.com/489202/191867652-49e32f79-3751-46f2-b7bc-4d6b0c39f0e0.png">

**Comment by hkirat** [comment]
I've added a temporary PR [here](https://github.com/coral-xyz/backpack/pull/939) to fix this but does it make sense for there to be a `custom input box` and a `disabled` button in case the input URL is invalid and a `back` button for the user to go back? Rather than using a prompt like we currently are.
